//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VitSettings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class SettingsMail : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsMail defaultInstance = ((SettingsMail)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsMail())));
        
        public static SettingsMail Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("imap.yandex.ru")]
        public string serverInAdres {
            get {
                return ((string)(this["serverInAdres"]));
            }
            set {
                this["serverInAdres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.yandex.ru;")]
        public string serverOutAdres {
            get {
                return ((string)(this["serverOutAdres"]));
            }
            set {
                this["serverOutAdres"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("993")]
        public int serverInPort {
            get {
                return ((int)(this["serverInPort"]));
            }
            set {
                this["serverInPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public int serverOutPort {
            get {
                return ((int)(this["serverOutPort"]));
            }
            set {
                this["serverOutPort"] = value;
            }
        }
    }
}
